language: python
cache: pip
sudo: required
dist: precise

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27 DDB=true CODECOV=true
    - python: pypy-5.6.0
      env: TOXENV=pypy DDB=true CODECOV=true
    - env: TOXENV=flake8
    - python: 3.6
      env: TOXENV=py36-mypy
  allow_failures:
    - env: TOXENV=py36-mypy

install:
- ${DDB:+make ddb}
- pip install tox ${CODECOV:+codecov}
script:
- tox -- ${CODECOV:+--with-coverage --cover-xml --cover-package=autopush}
after_success:
- ${CODECOV:+codecov}
notifications:
  slack:
    secure: vT9sWtUuxk28g6xYKAsQmiPZllErOYVfx5lcL+/jo1eRFrmbpYnyndT6s+FxGI1547oizZ0IqZbHVvB7BUoSJixXJyQJYXW2MchwN1UeHrey8mYpF1GNEaJT7FMfqSkxUU9gvAZ3IU7zstNeTLbfG1GkLuzybp0WAiHl/ocUTz8=
