language: python
sudo: required
dist: precise
python:
  - "2.7"
install:
  - virtualenv pypy
  - cd pypy/bin && ln -s python pypy && cd ../..
  - source pypy/bin/activate
  - make travis
script: tox -- --with-coverage --cover-xml --cover-package=autopush
after_success:
  - codecov
