language: python
sudo: false
python:
  - "pypy"
install:
  - pip install coverage nose mock moto codecov tox
script: tox -- --with-coverage --cover-xml --cover-package=autopush
after_success:
  - codecov
