version: '2'
services:
  autopush:
    build: .
    # If you do not wish to use a local build, comment out
    # the previous 'build:' line and uncomment the following
    # 'image:' line. This will use the latest production
    # built image.
    #image: mozilla/autopush
    hostname: autopush
    environment:
      - LOCAL_HOSTNAME=localhost
      - ROUTER_HOSTNAME=autopush
      - AWS_LOCAL_DYNAMODB=http://dynamodb:8000
      - HUMAN_LOGS=true
      - CRYPTO_KEY=${CRYPTO_KEY}
    ports:
      - "8080:8080"
      - "8081:8081"
    links:
      - dynamodb
    volumes:
      - ./boto-compose.cfg:/etc/boto.cfg:ro
  autoendpoint:
    build: .
    # If you do not wish to use a local build, comment out
    # the previous 'build:' line and uncomment the following
    # 'image:' line. This will use the latest production
    # built image.
    #image: mozilla/autopush
    hostname: autoendpoint
    command: autoendpoint
    environment:
      - HUMAN_LOGS=true
      - CRYPTO_KEY=${CRYPTO_KEY}
      - AWS_LOCAL_DYNAMODB=http://dynamodb:8000
    ports:
      - "8082:8082"
    links:
      - dynamodb
    volumes:
      - ./boto-compose.cfg:/etc/boto.cfg:ro
  dynamodb:
    image: peopleperhour/dynamodb
    hostname: dynamodb
    expose:
      - "8000"
