[package]
name = "autopush"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
bytes = "0.4"
env_logger = { version = "0.4", default-features = false }
error-chain = "0.10"
futures = "0.1"
httparse = "1.0"
hyper = "0.11"
libc = "0.2"
log = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
time = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"
tokio-service = "0.1"
tokio-tungstenite = { version = "0.3", default-features = false }
tungstenite = { version = "0.4", default-features = false }
uuid = { version = "0.5", features = ["serde", "v4"] }

[profile.release]
debug-assertions = true
