[package]
name = "autopush"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
bytes = "0.4"
cadence = "0.12.1"
chrono = "0.4"
env_logger = { version = "0.4", default-features = false }
error-chain = "0.10"
futures = "0.1"
httparse = "1.0"
hyper = "0.11"
libc = "0.2"
# log: Use this version for debug builds
#log = "0.3"
# log: Use this for release builds (leave in for commits)
log = { version = "0.3", features = ["max_level_trace", "release_max_level_warn"] }
openssl = "0.9"
sentry = "0.2.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
# slog: Use this first version for debug builds
#slog = { version = "2.0.12" , features = ["max_level_trace", "release_max_level_debug"] }
# slog: Use this for release builds (leave in for commits)
slog = "2.0.12"
slog-async = "2.1.0"
slog-term = "2.3.0"
slog-json = "2.0.2"
slog-scope = "4.0.0"
slog-stdlog = "3.0.2"
time = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"
tokio-openssl = "0.1"
tokio-service = "0.1"
tokio-tungstenite = { version = "0.4", default-features = false }
tungstenite = { version = "0.5", default-features = false }
uuid = { version = "0.5", features = ["serde", "v4"] }
woothee = "0.7.3"
